
- name: Commit and push
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add output/
    git commit -m "🔄 update Spotify summary" || echo "Nothing to commit"
    git push
